# Generated by Django 2.2.6 on 2019-10-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-created_at']},
        ),
    ]
