# Generated by Django 2.2.6 on 2019-10-22 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fans',
            field=models.ManyToManyField(related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
