# Generated by Django 2.2.6 on 2019-10-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20191022_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ('-created',)},
        ),
    ]
